spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chatdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
security:
    api-key: ${SECURITY_API_KEY:app-key}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
server:
  port: ${PORT:8080}
app:
  jwt:
    secret: ${JWT_SECRET:change-me}
    expiry-ms: 3600000

logging:
  level:
    root: INFO
    com.example.chat: DEBUG

